FROM public.ecr.aws/lambda/python:3.9-arm64
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY requirements.txt  .
RUN python3.9 -m pip install -r requirements.txt
CMD ["lambda_function.lambda_handler"] 
